---
title: "Geospatial Analytics and Applications (in R)"
author: "Federico Jose Rodriguez"
---

Welcome to my website for my work in the course [**ISSS 626 - Geospatial Analytics and Applications**]{.underline} during the August term of 2024 under **Dr Kam Tin Seong**.

The course covers theory and methods of geospatial analysis and the tools in R to implement such analyses.

## Hands-On Exercises

Hands-on exercises are assigned before each lesson to give us hands-on experience in using R on the geospatial analysis methods and functions we learned. We are given step-by-step instructions and explanations (through Dr Kam's online [book](https://r4gdsa.netlify.app/ "R for Geospatial Data Science and Analytics by Dr Kam")) which complement our pre-class reading, and prepares us for the in-class exercises.

1.  [Geospatial Data Wrangling with R](Hands-on/Hands-on_Ex01/Hands-on_Ex01.html) (for Session 1, 26 Aug '24)

2.  [Choropleth Mapping with R](Hands-on/Hands-on_Ex02/Hands-on_Ex02.html) (for Session 1, 26 Aug '24)

3.  [1st Order Spatial Point Patterns Analysis Methods](Hands-on/Hands-on_Ex03/Hands-on_Ex03.html) (for Session 2, 2 Sept '24)

4.  [2nd Order Spatial Point Patterns Analysis Methods](Hands-on/Hands-on_Ex04/Hands-on_Ex04.html) (for Session 2, 2 Sept '24)

5.  [Network Constrained Spatial Point Pattern Analysis](Hands-on/Hands-on_Ex05/Hands-on_Ex05.html) (for Session 3, 9 Sept 2024)

6.  [Spatial Weights and Applications](Hands-on/Hands-on_Ex06/Hands-on_Ex06.html) (for Session 4, 16 Sept 2024)

7.  [Global Measures of Spatial Autocorrelation](Hands-on/Hands-on_Ex07/Hands-on_Ex07.html) (for Session 5, 23 Sept 2024)

8.  [Local Measures of Spatial Autocorrelation](Hands-on/Hands-on_Ex08/Hands-on_Ex08.html) (for Session 5, 23 Sept 2024)

9.  [Geographical Segmentation with Spatially Constrained Clustering Techniques](Hands-on/Hands-on_Ex09/Hands-on_Ex09.html) (for Session 6, 30 Sept 2024)

## In-Class Exercises

In each session, we go through a hands-on exercise to revise the readings for the lesson. The objective of these is to further reinforce the concepts and tools learned in the readings and in the take-home exercise. These will also go further into the analysis and interpretation of results.

1.  [Introduction to Geospatial Analytics](In-class/In-class_Ex01/In-class_Ex01.html) (26 Aug '24)

2.  [Spatial Point Pattern Analysis](In-class/In-class_Ex02/In-class_Ex02.html) - Data Load for Take-home Exercise 1 (2 Sept '24)

3.  [Advanced Spatial Point Patterns Analysis](In-class/In-class_Ex03/In-class_Ex03.html) (9 Sept '24)

4.  [Spatial Autocorrelation](In-class/In-class_Ex04/In-class_Ex04.html) (23 Sept'24)

## Take-Home Exercises

Take-home exercises are where we students are able to apply the methods and techniques learned in class in real-world cases– using real-world data and aim to generate real insights.

For each of these, we are given a specific problem, objectives and a base data set. Each student will work on the problem independently, guided only by the previous exercises and lessons.

1.  [Geospatial Analysis for Public Good: A Data-driven Perspective on Road Traffic Accidents in the Bangkok Metropolitan Region](Take-home/Take-home_Ex01/Take-home_Ex01.html)
2.  [Discovering the Impact of COVID-19 on Thai tourism economy](Take-home/Take-home_Ex02/Take-home_Ex02.html)
