---
title: "Discovering Impact of COVID-19 on Thai Tourism Economy"
author: "Federico Jose Rodriguez"
date: "Sep 23 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

(Exercise Summary)

# A. Getting Started

## A.1 Background

WIP

## A.2 Objectives

WIP

## A.3 Data Sources

The following data sources are used for this analysis:

-   [Thailand Domestic Tourism Statistics](https://www.kaggle.com/datasets/thaweewatboy/thailand-domestic-tourism-statistics) from Kaggle covering the years 2019-2023 and are at province and month level across 8 indicators:

    1.  `no_tourist_all` - XXX

    2.  `no_tourist_foreign` - XXX

    3.  `no_tourist_occupied` - XXX

    4.  `no_tourist_thai` - XXX

    5.  `occupancy_rate` - XXX

    6.  `revenue_all` - XXX

    7.  `revenue_foreign` - XXX

    8.  `revenue_thai` - XXX

-   [Thailand-Subnational Administrative Boundaries](https://data.humdata.org/dataset/cod-ab-tha?) from Human Data Exchange in shapefile format

## A.4 Importing and Launching R Packages

(WIP) For this study, XXX R packages will be used. A description of the packages and the code, using `p_load()` of the **pacman** package, to import them is given below.

As we will be performing simulations in the analysis later, it is good practice to define a random seed to be used so that results are consistent for viewers of this report, and the results can be reproduced.

`{r} set.seed(1234)}`

# B. Data Loading and Preparation

WIP
